### ISSUE TITLE
Option to automatically delete all "empty" usernames

### ISSUE THREAD

**Issue by GoogleCodeExporter** [antville/antville#72] opened 2015-04-04 16:12 UTC
```
i.e.: all usernames without story/comment/image/file plus subscriptions
when the last login was a defineable number of days ago. 

This should facilitate getting the username of choice for people wanting to
register.
```

Original issue reported on code.google.com by `kinomu.w...@gmail.com` on 13 Jan 2010 at 4:35

**Comment by p3k** [comment] 2020-04-13 13:58
duplicate of #62; closing

**Closed by p3k** 2020-04-13 13:58 UTC
Labels: duplicate, enhancement
